import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';
import AppProvider from "./app-provider";
const inter = Inter({ subsets: ["latin"] });
import Head from "next/head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="stylesheet" href="/_next/static/css/app/layout.css?v=1714965362265" data-precedence="next_static/css/app/layout.css"></link>
      </Head>
      <body className={inter.className}>
        <ToastContainer />
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
